stages:
  - build-app
  - build-image

build app:
  stage: build-app
  image: node:8
  script:
    - yarn
    - yarn lint
    - yarn build
  cache:
    paths:
      - node_modules
  artifacts:
    paths:
      - .next
      - production-server
    expire_in: 1 day

build image:
  stage: build-image
  image: docker:latest
  services:
   - docker:dind
  script:
    - docker info
    - echo $CI_REGISTRY_PASSWORD | docker login --username $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - docker pull $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME || docker pull $CI_REGISTRY_IMAGE:master || true
    - docker build --pull --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --shm-size 256M .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
 